language: android
jdk: oraclejdk7
before_install:
 - chmod +x gradlew

env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

script: ./gradlew assembleDebug
